import { readFileSync } from "node:fs";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import {
	clearCanvasColorCache,
	getCanvasColor,
	getCanvasColorRgba,
} from "../canvas-colors";

/**
 * Golden-vector characterization test for the oklch -> sRGB math in
 * `src/shared/lib/canvas-colors.ts`.
 *
 * WHY: the conversion is hand-rolled matrix math (oklch polar -> oklab
 * cartesian, the LMS cube terms, the LMS -> linear-sRGB matrix, then the
 * 1.055*x^(1/2.4) - 0.055 gamma transfer with its 0.0031308 knee). A port to
 * another language will re-derive those constants from a different reference
 * and land a LSB or two off, or put the knee on the wrong side of the
 * comparison. These vectors pin the exact current behaviour.
 *
 * TOLERANCE: none. Outputs are the module's `rgb(...)` / `rgba(...)` strings,
 * whose channels are already `Math.round`ed to integers, so comparison is exact
 * string equality. A port that differs by one 8-bit level will fail here, which
 * is the point.
 *
 * The pure converter (`oklchToRgb` / `parseToRgb`) is module-private, so the
 * vectors are driven through `getCanvasColor` with `getComputedStyle` stubbed
 * to return the color string under test. The cache is cleared before each
 * probe so every case exercises the math rather than a memoized result.
 *
 * ---- HOW THE GOLDENS WERE PRODUCED (do not run at test time) ----
 * `harness/goldens/canvas-colors.json` was generated by a throwaway bun script
 * that stubbed `globalThis.document` / `globalThis.getComputedStyle` exactly as
 * this file does, then enumerated (no PRNG — a deterministic sweep):
 *   - L in {0, cbrt(0.0031308) +/- 1e-5, 0.25, 0.5, 0.62, 0.75, 1}
 *     (the two middle values straddle the achromatic gamma knee)
 *   - C in {0, 0.01, 0.1, 0.2, 0.37}  (0.37 is far out of gamut, pinning clamps)
 *   - H in {0, 15, ..., 345, 359.999}
 * emitting one case per (L, C) with the hue sweep as an output array, plus a
 * hand-authored string corpus and a few `getCanvasColorRgba` cases.
 * To regenerate: re-run that script and overwrite the JSON. This test only
 * reads it.
 */

type GoldenCase = {
	case: string;
	input: unknown;
	output: unknown;
};

const GOLDEN_PATH = path.resolve(
	import.meta.dirname,
	"../../../../harness/goldens/canvas-colors.json",
);
const goldens: GoldenCase[] = JSON.parse(readFileSync(GOLDEN_PATH, "utf8"));

let cssValue = "";
let originalDocument: unknown;
let originalGetComputedStyle: unknown;

beforeAll(() => {
	const g = globalThis as Record<string, unknown>;
	originalDocument = g.document;
	originalGetComputedStyle = g.getComputedStyle;
	g.document = { documentElement: {} };
	g.getComputedStyle = () => ({ getPropertyValue: () => cssValue });
});

afterAll(() => {
	const g = globalThis as Record<string, unknown>;
	g.document = originalDocument;
	g.getComputedStyle = originalGetComputedStyle;
});

/** Feed `value` through the module as if it were the computed CSS variable. */
function convert(value: string): string {
	cssValue = value;
	clearCanvasColorCache();
	return getCanvasColor("--probe");
}

function convertRgba(value: string, alpha: number): string {
	cssValue = value;
	clearCanvasColorCache();
	return getCanvasColorRgba("--probe", alpha);
}

function actualFor(golden: GoldenCase): unknown {
	if (golden.case.startsWith("oklch sweep ")) {
		const { l, c, hues } = golden.input as {
			l: number;
			c: number;
			hues: number[];
		};
		return hues.map((h) => convert(`oklch(${l} ${c} ${h})`));
	}
	if (golden.case.startsWith("rgba ")) {
		const { value, alpha } = golden.input as { value: string; alpha: number };
		return convertRgba(value, alpha);
	}
	return convert(golden.input as string);
}

describe("canvas-colors golden vectors", () => {
	it("has a non-degenerate golden corpus", () => {
		expect(goldens.length).toBeGreaterThanOrEqual(15);
		expect(new Set(goldens.map((g) => g.case)).size).toBe(goldens.length);
	});

	for (const golden of goldens) {
		it(golden.case, () => {
			expect(actualFor(golden)).toEqual(golden.output);
		});
	}
});
