import { describe, expect, it } from "vitest";
import goldens from "../../../../../harness/goldens/track-editor-timeline-constants.json";
import {
	computeBottomAnchoredLayout,
	computeLayout,
	getPatternColor,
	patternColors,
	TRACK_HEIGHT,
} from "../timeline-constants";

/**
 * Golden-vector characterization test for the timeline coordinate system.
 *
 * `computeLayout` / `computeBottomAnchoredLayout` are the entire vertical
 * coordinate system of the track-editor timeline; the GPUI port has to
 * reproduce them exactly. The risk is concentrated in:
 *   - `Math.round` on trackHeight / annotationLaneHeight (zoomY is a step
 *     function; JS rounds .5 toward +Infinity, so -40.5 -> -40 while Rust's
 *     f64::round gives -41),
 *   - the bottom-anchoring offset `totalHeight - naturalHeight`, which is only
 *     nonzero when the viewport exceeds the content,
 *   - `getPatternColor`'s `hash * 31 + charCode | 0` rolling hash, which needs
 *     explicit i32 wrapping in Rust and whose `Math.abs` has an edge case at
 *     i32::MIN (JS yields 2147483648, which is not an i32 at all).
 *
 * This test REGENERATES NOTHING. It loads recorded outputs and asserts the
 * current module still produces them.
 *
 * Tolerance: exact. Every recorded value is either an integer (Math.round
 * output, or a sum of integers) or an exactly-reproducible IEEE-754 double
 * (the `product` diagnostics, fractional viewport heights). There is no
 * accumulation, so no epsilon is warranted; a float drift here is a real
 * behavior change and should fail.
 *
 * ---------------------------------------------------------------------------
 * HOW THE GOLDENS WERE PRODUCED
 * ---------------------------------------------------------------------------
 * harness/goldens/track-editor-timeline-constants.json was generated by a
 * throwaway bun script that imported this module and enumerated (no
 * randomness beyond a seeded PRNG):
 *   - computeLayout over zoomY = MIN_ZOOM_Y..MAX_ZOOM_Y at 0.01 steps;
 *   - computeLayout over every .5-tie candidate z = (2k+1)/160 (where
 *     80*z nominally lands on a half), recording the float product too;
 *   - scalar computeLayout cases: clamp endpoints, 0, negatives, out-of-range;
 *   - computeBottomAnchoredLayout over 10 zoomY values x layerCount in
 *     {0,1,2,7,64} x viewportHeight in {0, 100, natural-1, natural,
 *     natural+1, 4000} so both sides of the max() are exercised;
 *   - getPatternColor over fixed real-shaped ids (uuids, snake_case, empty,
 *     single char, 512-char, non-ASCII) plus 200 mulberry32(0x5eed) ids;
 *   - getPatternColor over ids hand-solved (by inverting the last three chars
 *     of the rolling hash) to land the intermediate hash exactly on i32::MIN,
 *     i32::MIN+1, i32::MAX, 0 and -1.
 * To regenerate after an intentional behavior change, re-run that enumeration
 * and overwrite the JSON — never regenerate inside this test.
 */

type Case = {
	case: string;
	fn: string;
	input: Record<string, unknown> | null;
	output: unknown;
};
const cases = goldens as Case[];

// Mirror of the module's private rolling hash, recorded alongside each color
// so a hash-level regression is visible even when the color bucket is stable.
function hashOf(s: string): number {
	let h = 0;
	for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
	return h;
}

function actualFor(c: Case): unknown {
	const input = (c.input ?? {}) as Record<string, unknown>;
	switch (c.fn) {
		case "computeLayout":
			return computeLayout(input.zoomY as number);
		case "computeLayoutTable":
			return (input.zoomY as number[]).map(computeLayout);
		case "computeLayoutTieTable":
			return (input.zoomY as number[]).map((z) => ({
				product: TRACK_HEIGHT * z,
				layout: computeLayout(z),
			}));
		case "computeBottomAnchoredLayout":
			return computeBottomAnchoredLayout(
				input.zoomY as number,
				input.layerCount as number,
				input.viewportHeight as number,
			);
		case "bottomAnchoredTable":
			return (
				input.args as {
					zoomY: number;
					layerCount: number;
					viewportHeight: number;
				}[]
			).map((a) =>
				computeBottomAnchoredLayout(a.zoomY, a.layerCount, a.viewportHeight),
			);
		case "patternColorTable":
			return (input.ids as string[]).map((id) => ({
				id,
				hash: hashOf(id),
				color: getPatternColor(id),
			}));
		case "patternColorExtremeTable":
			return (input.ids as { name: string; id: string }[]).map((row) => ({
				name: row.name,
				id: row.id,
				hash: hashOf(row.id),
				absHash: Math.abs(hashOf(row.id)),
				color: getPatternColor(row.id),
			}));
		case "palette":
			return patternColors;
		default:
			throw new Error(`unknown golden fn: ${c.fn}`);
	}
}

describe("timeline-constants golden vectors", () => {
	it("golden file is present and in range", () => {
		expect(cases.length).toBeGreaterThanOrEqual(15);
		expect(cases.length).toBeLessThanOrEqual(60);
	});

	for (const c of cases) {
		it(c.case, () => {
			expect(actualFor(c)).toEqual(c.output);
		});
	}
});
