// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioCrop = { startSeconds: number; endSeconds: number };

export type BeatGrid = { beats: Array<number>; downbeats: Array<number> };

export type Edge = {
	id: string;
	fromNode: string;
	fromPort: string;
	toNode: string;
	toPort: string;
};

export type Graph = { nodes: Array<NodeInstance>; edges: Array<Edge> };

export type MelSpec = {
	width: number;
	height: number;
	data: Array<number>;
	beatGrid: BeatGrid | null;
};

export type NodeInstance = {
	id: string;
	typeId: string;
	params: Record<string, unknown>;
	positionX: number | null;
	positionY: number | null;
};

export type NodeTypeDef = {
	id: string;
	name: string;
	description: string | null;
	category: string | null;
	inputs: Array<PortDef>;
	outputs: Array<PortDef>;
	params: Array<ParamDef>;
};

export type ParamDef = {
	id: string;
	name: string;
	paramType: ParamType;
	defaultNumber: number | null;
	defaultText: string | null;
};

export type ParamType = "Number" | "Text";

export type PatternDetail = {
	id: number;
	name: string;
	description: string | null;
	graphJson: string;
	createdAt: string;
	updatedAt: string;
};

export type PatternEntrySummary = {
	durationSeconds: number;
	sampleRate: number;
	sampleCount: number;
	beatGrid: BeatGrid | null;
	crop: AudioCrop | null;
};

export type PatternSummary = {
	id: number;
	name: string;
	description: string | null;
	createdAt: string;
	updatedAt: string;
};

export type PlaybackStateSnapshot = {
	activeNodeId: string | null;
	isPlaying: boolean;
	currentTime: number;
	durationSeconds: number;
};

export type PortDef = { id: string; name: string; portType: PortType };

export type PortType = "Intensity" | "Audio" | "BeatGrid" | "Series";

export type Series = {
	dim: number;
	labels: Array<string> | null;
	samples: Array<SeriesSample>;
};

export type SeriesSample = {
	time: number;
	values: Array<number>;
	label: string | null;
};

export type TrackSummary = {
	id: number;
	trackHash: string;
	title: string | null;
	artist: string | null;
	album: string | null;
	trackNumber: number | null;
	discNumber: number | null;
	durationSeconds: number | null;
	filePath: string;
	albumArtPath: string | null;
	albumArtMime: string | null;
	albumArtData: string | null;
	createdAt: string;
	updatedAt: string;
};
