pub mod agent;
pub mod agent_execution;
pub mod annotation_preview;
mod artnet;
pub mod audio;
mod beat_worker;
mod canonical_json;
mod classifier_worker;
mod cmd_util;
mod compositor;
/// Compile a saved score for read-only render replay and diagnostics.
pub use compositor::build_score_scene;
pub mod config;
mod controller_compositor;
mod controller_manager;
pub mod database;
pub mod dispatch;
mod engine_dj;
pub mod eval;
mod ffmpeg_env;
pub mod fixtures;
mod genre_worker;
pub mod headless_host;
pub mod host_audio;
mod mert_worker;
mod mixer_manager;
pub mod models;
mod n2n_worker;
pub mod node_graph;
mod preprocessing;
pub use preprocessing::AnalysisTaskGroup;
mod prodjlink_manager;
pub mod python_env;
pub mod recording;
mod rekordbox;
mod render_engine;
mod root_worker;
pub mod services;
pub mod settings;
pub mod stage_render;
mod stagelinq_manager;
mod stem_worker;
pub mod storage;
mod sync;
mod topo;
/// The venue graph: loading it, solving it, and converting what came before.
pub mod venue_graph;

/// The version shared by the GPUI host and backend tools.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
