//! Emits the catalog's TypeScript binding, and the golden the TS side is
//! checked against.
//!
//! The catalog is Rust ([`luma_scene::catalog`]); the React stage builder is a
//! consumer of it. Rather than a second hand-authored copy — which is what
//! `src/features/stage/lib/stage-meshes.ts` used to be, and why it drifted —
//! this test writes:
//!
//!   - `src/features/stage/lib/catalog.generated.ts`, the data itself, and
//!   - `harness/goldens/stage-catalog.json`, every piece's sockets *resolved*
//!     against one canonical bounding box.
//!
//! The TypeScript test `catalog.golden.test.ts` reads both: it resolves the
//! generated defs with the TS implementation and compares to the golden, which
//! is what proves the two languages agree about the data *and* the algorithm.
//! A real GLB is deliberately not involved — the bbox is an input to both
//! sides, so pinning one makes the comparison about the code under test rather
//! than about two glTF loaders.
//!
//! Run `cargo test -p luma-scene` after editing the catalog. The test rewrites
//! both files and then fails if they changed, so a stale binding cannot be
//! committed silently.

use luma_scene::aabb::DAabb;
use luma_scene::catalog::{pieces, Geometry, PaletteGroup, Piece};
use luma_scene::sockets::{
    resolve_socket, BboxAnchor, ResolvedSocket, RollFreedom, SocketDef, SocketKind, SocketType,
};
use serde_json::{json, Map, Value};
use std::path::{Path, PathBuf};

/// Asymmetric, off-centre, and not a unit anything: a bbox that would let a
/// sign error, a centre/size mix-up or a half-extent mistake pass is no test.
const GOLDEN_BBOX: [[f64; 3]; 2] = [[-0.7, -0.1, -0.35], [1.3, 0.9, 0.65]];

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

/// Write `contents` to `path` and report whether it differed from what was
/// already there.
fn write_if_changed(path: PathBuf, contents: &str) -> bool {
    let same = std::fs::read_to_string(&path).is_ok_and(|old| old == contents);
    if !same {
        std::fs::write(&path, contents).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    }
    !same
}

// ---------------------------------------------------------------------------
// TypeScript emission
// ---------------------------------------------------------------------------

fn ts_union(names: impl IntoIterator<Item = &'static str>) -> String {
    names
        .into_iter()
        .map(|n| format!("\n\t| {}", json!(n)))
        .collect()
}

fn vec3(v: glam::DVec3) -> Value {
    json!([v.x, v.y, v.z])
}

fn roll(r: RollFreedom) -> Value {
    match r {
        RollFreedom::Fixed => json!({ "kind": "fixed" }),
        RollFreedom::Steps(deg) => json!({ "kind": "steps", "degrees": deg }),
        RollFreedom::Free => json!({ "kind": "free" }),
    }
}

fn socket_def(def: &SocketDef) -> Value {
    let mut o = Map::new();
    o.insert("name".into(), json!(def.name));
    o.insert("type".into(), json!(def.socket_type.as_str()));
    o.insert("anchor".into(), json!(def.anchor.as_str()));
    if let Some(v) = def.offset {
        o.insert("offset".into(), vec3(v));
    }
    if let Some(v) = def.normal {
        o.insert("normal".into(), vec3(v));
    }
    if let Some(v) = def.tangent {
        o.insert("tangent".into(), vec3(v));
    }
    o.insert("mode".into(), json!(def.mode.as_str()));
    if let Some(r) = def.roll {
        o.insert("roll".into(), roll(r));
    }
    Value::Object(o)
}

fn geometry(g: Geometry) -> Value {
    match g {
        Geometry::Mesh { path } => json!({ "kind": "mesh", "path": path }),
        Geometry::Procedural(family) => {
            json!({ "kind": "procedural", "family": family.as_str() })
        }
    }
}

fn piece(p: &Piece) -> Value {
    json!({
        "id": p.id,
        "kind": p.kind.as_str(),
        "displayName": p.display_name,
        "paletteGroup": p.palette_group.as_str(),
        "geometry": geometry(p.geometry),
        "sockets": p.sockets.iter().map(socket_def).collect::<Vec<_>>(),
    })
}

fn map_over_socket_types(f: impl Fn(SocketType) -> Value) -> Value {
    Value::Object(
        SocketType::ALL
            .iter()
            .map(|t| (t.as_str().to_string(), f(*t)))
            .collect(),
    )
}

fn typescript() -> String {
    let pretty = |v: &Value| {
        serde_json::to_string_pretty(v)
            .expect("json")
            .replace("  ", "\t")
    };
    format!(
        r#"// GENERATED by `cargo test -p luma-scene --test binding`. DO NOT EDIT.
//
// The stage catalog lives in `gpui/crates/scene/src/catalog.rs`; this file is
// its TypeScript projection, and `harness/goldens/stage-catalog.json` proves
// the two agree. Edit the Rust, rerun the test, commit both.

/** A named point on a piece. What it may attach to is derived, never listed. */
export type SocketType ={socket_types};

/** The equivalence class two sockets must share before they can mate. */
export type SocketKind ={socket_kinds};

/**
 * Which half of a joint a socket is. `male` is a plug and is only ever held,
 * `female` a receptacle and only ever a host, `neutral` self-mates.
 */
export type Polarity = "male" | "female" | "neutral";

/** How much a mated piece may still turn about the socket normal. */
export type RollFreedom =
	| {{ kind: "fixed" }}
	| {{ kind: "steps"; degrees: number }}
	| {{ kind: "free" }};

/** Named anchor points on an axis-aligned bbox: centroid, faces, edges, corners. */
export type BboxAnchor ={anchors};

/** How two mating sockets meet — see `sockets.ts`. */
export type SocketMode = "face" | "edge";

export type Vec3Tuple = [number, number, number];

/** Authored socket, before bbox resolution. */
export interface SocketDef {{
	name: string;
	type: SocketType;
	anchor: BboxAnchor;
	offset?: Vec3Tuple;
	normal?: Vec3Tuple;
	tangent?: Vec3Tuple;
	/** Absent means `"face"` — the golden vectors omit it where it defaults. */
	mode?: SocketMode;
	/** Overrides `SOCKET_ROLL[type]` for this one socket. */
	roll?: RollFreedom;
}}

export type PieceKind ={piece_kinds};

export type PaletteGroup ={palette_groups};

/** Where a piece's shape comes from. Procedural families carry no parameters here. */
export type Geometry =
	| {{ kind: "mesh"; path: string }}
	| {{ kind: "procedural"; family: "truss" | "corner" | "hinge" }};

export interface CatalogPiece {{
	id: string;
	kind: PieceKind;
	displayName: string;
	paletteGroup: PaletteGroup;
	geometry: Geometry;
	/** Empty for procedural pieces, whose sockets come from the generator. */
	sockets: SocketDef[];
}}

export const SOCKET_TYPES: SocketType[] = {socket_type_list};

export const SOCKET_KIND: Record<SocketType, SocketKind> = {socket_kind_map};

export const SOCKET_POLARITY: Record<SocketType, Polarity> = {socket_polarity_map};

export const SOCKET_ROLL: Record<SocketType, RollFreedom> = {socket_roll_map};

/** Palette draw order. */
export const PALETTE_GROUP_ORDER: PaletteGroup[] = {palette_order};

export const CATALOG: CatalogPiece[] = {pieces};
"#,
        socket_types = ts_union(SocketType::ALL.map(SocketType::as_str)),
        socket_kinds = ts_union(SocketKind::ALL.map(SocketKind::as_str)),
        anchors = ts_union(BboxAnchor::ALL.map(BboxAnchor::as_str)),
        piece_kinds = ts_union(
            pieces()
                .iter()
                .map(|p| p.kind.as_str())
                .collect::<std::collections::BTreeSet<_>>()
        ),
        palette_groups = ts_union(PaletteGroup::ALL.map(PaletteGroup::as_str)),
        socket_type_list = pretty(&json!(SocketType::ALL
            .iter()
            .map(|t| t.as_str())
            .collect::<Vec<_>>())),
        socket_kind_map = pretty(&map_over_socket_types(|t| json!(t.kind().as_str()))),
        socket_polarity_map = pretty(&map_over_socket_types(|t| json!(t.polarity().as_str()))),
        socket_roll_map = pretty(&map_over_socket_types(|t| roll(t.roll()))),
        palette_order = pretty(&json!(PaletteGroup::ALL
            .iter()
            .map(|g| g.as_str())
            .collect::<Vec<_>>())),
        pieces = pretty(&json!(pieces().iter().map(piece).collect::<Vec<_>>())),
    )
}

// ---------------------------------------------------------------------------
// Golden emission
// ---------------------------------------------------------------------------

fn resolved(s: &ResolvedSocket) -> Value {
    json!({
        "name": s.name,
        "type": s.socket_type.as_str(),
        "mode": s.mode.as_str(),
        "position": vec3(s.position),
        "normal": vec3(s.normal),
        "tangent": vec3(s.tangent),
        "outward": vec3(s.outward),
        "roll": roll(s.roll),
    })
}

fn golden() -> String {
    let bbox = DAabb::new(
        glam::DVec3::from_array(GOLDEN_BBOX[0]),
        glam::DVec3::from_array(GOLDEN_BBOX[1]),
    );
    let pieces: Vec<Value> = pieces()
        .iter()
        .filter(|p| !p.geometry.is_procedural())
        .map(|p| {
            json!({
                "id": p.id,
                "sockets": p.sockets
                    .iter()
                    .map(|d| resolved(&resolve_socket(d, &bbox)))
                    .collect::<Vec<_>>(),
            })
        })
        .collect();
    let mates: Vec<Value> = SocketType::ALL
        .iter()
        .flat_map(|held| {
            SocketType::ALL
                .iter()
                .filter(|host| held.mates(**host))
                .map(|host| json!([held.as_str(), host.as_str()]))
                .collect::<Vec<_>>()
        })
        .collect();
    let doc = json!({
        "bbox": GOLDEN_BBOX,
        "pieces": pieces,
        // Every ordered pair the polarity rule admits, so the TS predicate is
        // pinned to the Rust one and not merely to its own reimplementation.
        "mates": mates,
    });
    serde_json::to_string_pretty(&doc).expect("json") + "\n"
}

#[test]
fn binding_and_golden_are_current() {
    let ts_path = repo_root().join("src/features/stage/lib/catalog.generated.ts");
    let golden_path = repo_root().join("harness/goldens/stage-catalog.json");

    let ts_changed = write_if_changed(ts_path, &typescript());
    let golden_changed = write_if_changed(golden_path, &golden());

    assert!(
        !ts_changed && !golden_changed,
        "the catalog binding was stale and has been rewritten \
         (ts: {ts_changed}, golden: {golden_changed}) — review and commit it"
    );
}
