// GENERATED by `cargo test -p luma-scene --test binding`. DO NOT EDIT.
//
// The stage catalog lives in `gpui/crates/scene/src/catalog.rs`; this file is
// its TypeScript projection, and the test rewrites it and fails if it changed —
// which is what keeps the two from drifting. Edit the Rust, rerun the test,
// commit the result.

/** A named point on a piece. What it may attach to is derived, never listed. */
export type SocketType =
	| "grab"
	| "floor_top"
	| "floor_edge"
	| "floor_corner"
	| "truss_end"
	| "stand_top"
	| "stand_bottom"
	| "speaker_mount"
	| "equipment_mount"
	| "bottom_mount"
	| "rail_end"
	| "cable_end"
	| "ground";

/** The equivalence class two sockets must share before they can mate. */
export type SocketKind =
	| "surface"
	| "truss_end"
	| "edge"
	| "cable_end"
	| "grab";

/**
 * Which half of a joint a socket is. `male` is a plug and is only ever held,
 * `female` a receptacle and only ever a host, `neutral` self-mates.
 */
export type Polarity = "male" | "female" | "neutral";

/** How much a mated piece may still turn about the socket normal. */
export type RollFreedom =
	| { kind: "fixed" }
	| { kind: "steps"; degrees: number }
	| { kind: "free" };

/** Named anchor points on an axis-aligned bbox: centroid, faces, edges, corners. */
export type BboxAnchor =
	| "center"
	| "top"
	| "bottom"
	| "front"
	| "back"
	| "left"
	| "right"
	| "top_front"
	| "top_back"
	| "top_left"
	| "top_right"
	| "bottom_front"
	| "bottom_back"
	| "bottom_left"
	| "bottom_right"
	| "front_left"
	| "front_right"
	| "back_left"
	| "back_right"
	| "top_front_left"
	| "top_front_right"
	| "top_back_left"
	| "top_back_right"
	| "bottom_front_left"
	| "bottom_front_right"
	| "bottom_back_left"
	| "bottom_back_right";

/** How two mating sockets meet — see `sockets.ts`. */
export type SocketMode = "face" | "edge";

export type Vec3Tuple = [number, number, number];

/** Authored socket, before bbox resolution. */
export interface SocketDef {
	name: string;
	type: SocketType;
	anchor: BboxAnchor;
	offset?: Vec3Tuple;
	normal?: Vec3Tuple;
	tangent?: Vec3Tuple;
	/** Absent means `"face"` — the golden vectors omit it where it defaults. */
	mode?: SocketMode;
	/** Overrides `SOCKET_ROLL[type]` for this one socket. */
	roll?: RollFreedom;
}

export type PieceKind =
	| "cable_cover"
	| "cdj"
	| "floor"
	| "guardrail"
	| "mixer"
	| "speaker"
	| "stand"
	| "truss";

export type PaletteGroup =
	| "Stage"
	| "Trusses"
	| "Speakers"
	| "Equipment"
	| "Accessories";

/** Where a piece's shape comes from. Procedural families carry no parameters here. */
export type Geometry =
	| { kind: "mesh"; path: string }
	| { kind: "procedural"; family: "truss" | "corner" | "hinge" };

export interface CatalogPiece {
	id: string;
	kind: PieceKind;
	displayName: string;
	paletteGroup: PaletteGroup;
	geometry: Geometry;
	/** Empty for procedural pieces, whose sockets come from the generator. */
	sockets: SocketDef[];
}

export const SOCKET_TYPES: SocketType[] = [
	"grab",
	"floor_top",
	"floor_edge",
	"floor_corner",
	"truss_end",
	"stand_top",
	"stand_bottom",
	"speaker_mount",
	"equipment_mount",
	"bottom_mount",
	"rail_end",
	"cable_end",
	"ground"
];

export const SOCKET_KIND: Record<SocketType, SocketKind> = {
	"bottom_mount": "surface",
	"cable_end": "cable_end",
	"equipment_mount": "surface",
	"floor_corner": "truss_end",
	"floor_edge": "edge",
	"floor_top": "surface",
	"grab": "grab",
	"ground": "surface",
	"rail_end": "edge",
	"speaker_mount": "surface",
	"stand_bottom": "surface",
	"stand_top": "surface",
	"truss_end": "truss_end"
};

export const SOCKET_POLARITY: Record<SocketType, Polarity> = {
	"bottom_mount": "male",
	"cable_end": "neutral",
	"equipment_mount": "male",
	"floor_corner": "female",
	"floor_edge": "neutral",
	"floor_top": "female",
	"grab": "female",
	"ground": "female",
	"rail_end": "neutral",
	"speaker_mount": "male",
	"stand_bottom": "male",
	"stand_top": "female",
	"truss_end": "neutral"
};

export const SOCKET_ROLL: Record<SocketType, RollFreedom> = {
	"bottom_mount": {
		"kind": "free"
	},
	"cable_end": {
		"kind": "fixed"
	},
	"equipment_mount": {
		"kind": "free"
	},
	"floor_corner": {
		"kind": "fixed"
	},
	"floor_edge": {
		"kind": "fixed"
	},
	"floor_top": {
		"kind": "free"
	},
	"grab": {
		"kind": "free"
	},
	"ground": {
		"kind": "free"
	},
	"rail_end": {
		"kind": "fixed"
	},
	"speaker_mount": {
		"kind": "free"
	},
	"stand_bottom": {
		"kind": "free"
	},
	"stand_top": {
		"kind": "free"
	},
	"truss_end": {
		"kind": "fixed"
	}
};

/** Palette draw order. */
export const PALETTE_GROUP_ORDER: PaletteGroup[] = [
	"Stage",
	"Trusses",
	"Speakers",
	"Equipment",
	"Accessories"
];

export const CATALOG: CatalogPiece[] = [
	{
		"displayName": "Stage Deck 1×1m",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/stage_praticavel_1x1.glb"
		},
		"id": "stage_lab/stage_praticavel_1x1.glb",
		"kind": "floor",
		"paletteGroup": "Stage",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "bottom",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "bottom_mount"
			},
			{
				"anchor": "top",
				"mode": "face",
				"name": "top",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"type": "floor_top"
			},
			{
				"anchor": "top_front",
				"mode": "edge",
				"name": "edge_front",
				"tangent": [
					1.0,
					0.0,
					0.0
				],
				"type": "floor_edge"
			},
			{
				"anchor": "top_back",
				"mode": "edge",
				"name": "edge_back",
				"tangent": [
					1.0,
					0.0,
					0.0
				],
				"type": "floor_edge"
			},
			{
				"anchor": "top_left",
				"mode": "edge",
				"name": "edge_left",
				"tangent": [
					0.0,
					0.0,
					1.0
				],
				"type": "floor_edge"
			},
			{
				"anchor": "top_right",
				"mode": "edge",
				"name": "edge_right",
				"tangent": [
					0.0,
					0.0,
					1.0
				],
				"type": "floor_edge"
			},
			{
				"anchor": "top_front_left",
				"mode": "face",
				"name": "corner_fl",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					0.15,
					0.0,
					-0.15
				],
				"type": "floor_corner"
			},
			{
				"anchor": "top_front_right",
				"mode": "face",
				"name": "corner_fr",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					-0.15,
					0.0,
					-0.15
				],
				"type": "floor_corner"
			},
			{
				"anchor": "top_back_left",
				"mode": "face",
				"name": "corner_bl",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					0.15,
					0.0,
					0.15
				],
				"type": "floor_corner"
			},
			{
				"anchor": "top_back_right",
				"mode": "face",
				"name": "corner_br",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					-0.15,
					0.0,
					0.15
				],
				"type": "floor_corner"
			}
		]
	},
	{
		"displayName": "Stage Deck 2×1m",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/stage_praticavel_2x1x1.glb"
		},
		"id": "stage_lab/stage_praticavel_2x1x1.glb",
		"kind": "floor",
		"paletteGroup": "Stage",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "bottom",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "bottom_mount"
			},
			{
				"anchor": "top",
				"mode": "face",
				"name": "top",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"type": "floor_top"
			},
			{
				"anchor": "top_front",
				"mode": "edge",
				"name": "edge_front",
				"tangent": [
					1.0,
					0.0,
					0.0
				],
				"type": "floor_edge"
			},
			{
				"anchor": "top_back",
				"mode": "edge",
				"name": "edge_back",
				"tangent": [
					1.0,
					0.0,
					0.0
				],
				"type": "floor_edge"
			},
			{
				"anchor": "top_left",
				"mode": "edge",
				"name": "edge_left",
				"tangent": [
					0.0,
					0.0,
					1.0
				],
				"type": "floor_edge"
			},
			{
				"anchor": "top_right",
				"mode": "edge",
				"name": "edge_right",
				"tangent": [
					0.0,
					0.0,
					1.0
				],
				"type": "floor_edge"
			},
			{
				"anchor": "top_front_left",
				"mode": "face",
				"name": "corner_fl",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					0.15,
					0.0,
					-0.15
				],
				"type": "floor_corner"
			},
			{
				"anchor": "top_front_right",
				"mode": "face",
				"name": "corner_fr",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					-0.15,
					0.0,
					-0.15
				],
				"type": "floor_corner"
			},
			{
				"anchor": "top_back_left",
				"mode": "face",
				"name": "corner_bl",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					0.15,
					0.0,
					0.15
				],
				"type": "floor_corner"
			},
			{
				"anchor": "top_back_right",
				"mode": "face",
				"name": "corner_br",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					-0.15,
					0.0,
					0.15
				],
				"type": "floor_corner"
			}
		]
	},
	{
		"displayName": "Truss · straight",
		"geometry": {
			"family": "truss",
			"kind": "procedural"
		},
		"id": "truss/straight",
		"kind": "truss",
		"paletteGroup": "Trusses",
		"sockets": []
	},
	{
		"displayName": "Truss · corner box",
		"geometry": {
			"family": "corner",
			"kind": "procedural"
		},
		"id": "truss/corner",
		"kind": "truss",
		"paletteGroup": "Trusses",
		"sockets": []
	},
	{
		"displayName": "Truss · hinge",
		"geometry": {
			"family": "hinge",
			"kind": "procedural"
		},
		"id": "truss/hinge",
		"kind": "truss",
		"paletteGroup": "Trusses",
		"sockets": []
	},
	{
		"displayName": "Yamaha DBR15",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/speaker_dbr15.glb"
		},
		"id": "stage_lab/speaker_dbr15.glb",
		"kind": "speaker",
		"paletteGroup": "Speakers",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "mount",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "speaker_mount"
			}
		]
	},
	{
		"displayName": "Dual 18\" Sub",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/speaker_dual18sub.glb"
		},
		"id": "stage_lab/speaker_dual18sub.glb",
		"kind": "speaker",
		"paletteGroup": "Speakers",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "mount",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "speaker_mount"
			}
		]
	},
	{
		"displayName": "Event 212A",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/speaker_event_212a.glb"
		},
		"id": "stage_lab/speaker_event_212a.glb",
		"kind": "speaker",
		"paletteGroup": "Speakers",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "mount",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "speaker_mount"
			}
		]
	},
	{
		"displayName": "JBL VTX V20",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/speaker_jbl_vtx_v20.glb"
		},
		"id": "stage_lab/speaker_jbl_vtx_v20.glb",
		"kind": "speaker",
		"paletteGroup": "Speakers",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "mount",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "speaker_mount"
			}
		]
	},
	{
		"displayName": "Speaker Stand",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/speaker_stand.glb"
		},
		"id": "stage_lab/speaker_stand.glb",
		"kind": "stand",
		"paletteGroup": "Accessories",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"offset": [
					0.1,
					0.0,
					0.0
				],
				"type": "grab"
			},
			{
				"anchor": "top",
				"mode": "face",
				"name": "top",
				"normal": [
					0.0,
					1.0,
					0.0
				],
				"offset": [
					0.1,
					0.0,
					0.0
				],
				"type": "stand_top"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "base",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"offset": [
					0.1,
					0.0,
					0.0
				],
				"type": "stand_bottom"
			}
		]
	},
	{
		"displayName": "CDJ-3000",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/cdj_3000x.glb"
		},
		"id": "stage_lab/cdj_3000x.glb",
		"kind": "cdj",
		"paletteGroup": "Equipment",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "mount",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "equipment_mount"
			}
		]
	},
	{
		"displayName": "DJM-A9 Mixer",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/mixer_djm_a9.glb"
		},
		"id": "stage_lab/mixer_djm_a9.glb",
		"kind": "mixer",
		"paletteGroup": "Equipment",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "mount",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "equipment_mount"
			}
		]
	},
	{
		"displayName": "Guardrail",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/guardrail.glb"
		},
		"id": "stage_lab/guardrail.glb",
		"kind": "guardrail",
		"paletteGroup": "Accessories",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "bottom",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "bottom_mount"
			},
			{
				"anchor": "left",
				"mode": "face",
				"name": "end_a",
				"normal": [
					-1.0,
					0.0,
					0.0
				],
				"offset": [
					0.012,
					0.0,
					0.0
				],
				"tangent": [
					0.0,
					0.0,
					1.0
				],
				"type": "rail_end"
			},
			{
				"anchor": "right",
				"mode": "face",
				"name": "end_b",
				"normal": [
					1.0,
					0.0,
					0.0
				],
				"offset": [
					-0.012,
					0.0,
					0.0
				],
				"tangent": [
					0.0,
					0.0,
					1.0
				],
				"type": "rail_end"
			}
		]
	},
	{
		"displayName": "Cable Cover",
		"geometry": {
			"kind": "mesh",
			"path": "stage_lab/cable_cover.glb"
		},
		"id": "stage_lab/cable_cover.glb",
		"kind": "cable_cover",
		"paletteGroup": "Accessories",
		"sockets": [
			{
				"anchor": "center",
				"mode": "face",
				"name": "grab",
				"type": "grab"
			},
			{
				"anchor": "bottom",
				"mode": "face",
				"name": "mount",
				"normal": [
					0.0,
					-1.0,
					0.0
				],
				"type": "equipment_mount"
			},
			{
				"anchor": "front",
				"mode": "face",
				"name": "end_front",
				"normal": [
					0.0,
					0.0,
					1.0
				],
				"offset": [
					0.0,
					0.0,
					-0.005
				],
				"tangent": [
					1.0,
					0.0,
					0.0
				],
				"type": "cable_end"
			},
			{
				"anchor": "back",
				"mode": "face",
				"name": "end_back",
				"normal": [
					0.0,
					0.0,
					-1.0
				],
				"offset": [
					0.0,
					0.0,
					0.005
				],
				"tangent": [
					1.0,
					0.0,
					0.0
				],
				"type": "cable_end"
			}
		]
	}
];
