use super::*;
pub fn get_node_types() -> Vec<NodeTypeDef> {
    vec![
        NodeTypeDef {
            id: "audio_input".into(),
            name: "Audio Input".into(),
            description: Some("Context-provided audio segment for this pattern instance.".into()),
            category: Some("Input".into()),
            inputs: vec![],
            outputs: vec![PortDef {
                id: "out".into(),
                name: "Audio".into(),
                port_type: PortType::Audio,
            }],
            params: vec![
                ParamDef {
                    id: "trackId".into(),
                    name: "Track".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "startTime".into(),
                    name: "Start Time (s)".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "endTime".into(),
                    name: "End Time (s)".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "beatGrid".into(),
                    name: "Beat Grid JSON".into(),
                    param_type: ParamType::Text,
                    default_number: None,
                    default_text: None,
                },
            ],
        },
        NodeTypeDef {
            id: "stem_splitter".into(),
            name: "Stem Splitter".into(),
            description: Some(
                "Loads cached stems for the incoming track and emits drums/bass/vocals/other."
                    .into(),
            ),
            category: Some("Audio".into()),
            inputs: vec![PortDef {
                id: "audio_in".into(),
                name: "Audio".into(),
                port_type: PortType::Audio,
            }],
            outputs: vec![
                PortDef {
                    id: "drums_out".into(),
                    name: "Drums".into(),
                    port_type: PortType::Audio,
                },
                PortDef {
                    id: "bass_out".into(),
                    name: "Bass".into(),
                    port_type: PortType::Audio,
                },
                PortDef {
                    id: "vocals_out".into(),
                    name: "Vocals".into(),
                    port_type: PortType::Audio,
                },
                PortDef {
                    id: "other_out".into(),
                    name: "Other".into(),
                    port_type: PortType::Audio,
                },
            ],
            params: vec![],
        },
        NodeTypeDef {
            id: "frequency_amplitude".into(),
            name: "Frequency Amplitude".into(),
            description: Some("Extracts amplitude at a specific frequency range.".into()),
            category: Some("Audio".into()),
            inputs: vec![PortDef {
                id: "audio_in".into(),
                name: "Audio".into(),
                port_type: PortType::Audio,
            }],
            outputs: vec![PortDef {
                id: "amplitude_out".into(),
                name: "Amplitude".into(),
                port_type: PortType::Signal,
            }],
            params: vec![ParamDef {
                id: "selected_frequency_ranges".into(),
                name: "Frequency Ranges (JSON)".into(),
                param_type: ParamType::Text,
                default_number: None,
                default_text: Some("[]".into()),
            }],
        },
        NodeTypeDef {
            id: "lowpass_filter".into(),
            name: "Lowpass Filter".into(),
            description: Some("Applies a lowpass filter to incoming audio.".into()),
            category: Some("Audio".into()),
            inputs: vec![PortDef {
                id: "audio_in".into(),
                name: "Audio".into(),
                port_type: PortType::Audio,
            }],
            outputs: vec![PortDef {
                id: "audio_out".into(),
                name: "Audio".into(),
                port_type: PortType::Audio,
            }],
            params: vec![ParamDef {
                id: "cutoff_hz".into(),
                name: "Cutoff (Hz)".into(),
                param_type: ParamType::Number,
                default_number: Some(200.0),
                default_text: None,
            }],
        },
        NodeTypeDef {
            id: "highpass_filter".into(),
            name: "Highpass Filter".into(),
            description: Some("Applies a highpass filter to incoming audio.".into()),
            category: Some("Audio".into()),
            inputs: vec![PortDef {
                id: "audio_in".into(),
                name: "Audio".into(),
                port_type: PortType::Audio,
            }],
            outputs: vec![PortDef {
                id: "audio_out".into(),
                name: "Audio".into(),
                port_type: PortType::Audio,
            }],
            params: vec![ParamDef {
                id: "cutoff_hz".into(),
                name: "Cutoff (Hz)".into(),
                param_type: ParamType::Number,
                default_number: Some(200.0),
                default_text: None,
            }],
        },
        NodeTypeDef {
            id: "beat_envelope".into(),
            name: "Beat Envelope".into(),
            description: Some("Generates rhythmic envelopes aligned to the beat grid.".into()),
            category: Some("Generator".into()),
            inputs: vec![
                PortDef {
                    id: "subdivision".into(),
                    name: "Subdivision".into(),
                    port_type: PortType::Signal,
                },
                PortDef {
                    id: "offset".into(),
                    name: "Beat Offset".into(),
                    port_type: PortType::Signal,
                },
            ],
            outputs: vec![PortDef {
                id: "out".into(),
                name: "Signal".into(),
                port_type: PortType::Signal,
            }],
            params: vec![
                ParamDef {
                    id: "subdivision".into(),
                    name: "Subdivision".into(),
                    param_type: ParamType::Number,
                    default_number: Some(1.0),
                    default_text: None,
                },
                ParamDef {
                    id: "only_downbeats".into(),
                    name: "Only Downbeats".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "offset".into(),
                    name: "Beat Offset".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "attack".into(),
                    name: "Attack Weight".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.3),
                    default_text: None,
                },
                ParamDef {
                    id: "decay".into(),
                    name: "Decay Weight".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.2),
                    default_text: None,
                },
                ParamDef {
                    id: "sustain".into(),
                    name: "Sustain Hold Weight".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.3),
                    default_text: None,
                },
                ParamDef {
                    id: "release".into(),
                    name: "Release Weight".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.2),
                    default_text: None,
                },
                ParamDef {
                    id: "sustain_level".into(),
                    name: "Sustain Level".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.7),
                    default_text: None,
                },
                ParamDef {
                    id: "attack_curve".into(),
                    name: "Attack Curve".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "decay_curve".into(),
                    name: "Decay Curve".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "amplitude".into(),
                    name: "Amplitude".into(),
                    param_type: ParamType::Number,
                    default_number: Some(1.0),
                    default_text: None,
                },
            ],
        },
        NodeTypeDef {
            id: "beat_pulses".into(),
            name: "Beat Pulses".into(),
            description: Some(
                "Emits subdivision-aligned pulse timestamps from the beat grid. Feed into ADSR for shaping."
                    .into(),
            ),
            category: Some("Generator".into()),
            inputs: vec![
                PortDef {
                    id: "subdivision".into(),
                    name: "Subdivision".into(),
                    port_type: PortType::Signal,
                },
                PortDef {
                    id: "offset".into(),
                    name: "Beat Offset".into(),
                    port_type: PortType::Signal,
                },
            ],
            outputs: vec![PortDef {
                id: "events_out".into(),
                name: "Events".into(),
                port_type: PortType::Events,
            }],
            params: vec![
                ParamDef {
                    id: "subdivision".into(),
                    name: "Subdivision".into(),
                    param_type: ParamType::Number,
                    default_number: Some(1.0),
                    default_text: None,
                },
                ParamDef {
                    id: "only_downbeats".into(),
                    name: "Only Downbeats".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "offset".into(),
                    name: "Beat Offset".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
            ],
        },
        NodeTypeDef {
            id: "drum_events".into(),
            name: "Drum Events".into(),
            description: Some(
                "Per-class drum onset timestamps from the n2n preprocessor.".into(),
            ),
            category: Some("Generator".into()),
            inputs: vec![],
            outputs: vec![
                PortDef {
                    id: "kick_out".into(),
                    name: "Kick".into(),
                    port_type: PortType::Events,
                },
                PortDef {
                    id: "snare_out".into(),
                    name: "Snare".into(),
                    port_type: PortType::Events,
                },
                PortDef {
                    id: "hat_out".into(),
                    name: "Hi-Hat".into(),
                    port_type: PortType::Events,
                },
                PortDef {
                    id: "cymbal_out".into(),
                    name: "Cymbal".into(),
                    port_type: PortType::Events,
                },
            ],
            params: vec![],
        },
        NodeTypeDef {
            id: "adsr".into(),
            name: "ADSR Envelope".into(),
            description: Some(
                "Shapes incoming events into an ADSR envelope. A/D/S/R are unitless ratios that sum to ~1; total duration is `Length` in beats (or the inter-event gap if Fit To Gap is on)."
                    .into(),
            ),
            category: Some("Signal".into()),
            inputs: vec![PortDef {
                id: "events_in".into(),
                name: "Events".into(),
                port_type: PortType::Events,
            }],
            outputs: vec![PortDef {
                id: "signal_out".into(),
                name: "Signal".into(),
                port_type: PortType::Signal,
            }],
            params: vec![
                ParamDef {
                    id: "attack".into(),
                    name: "Attack Ratio".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.1),
                    default_text: None,
                },
                ParamDef {
                    id: "decay".into(),
                    name: "Decay Ratio".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.4),
                    default_text: None,
                },
                ParamDef {
                    id: "sustain".into(),
                    name: "Sustain Ratio".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "release".into(),
                    name: "Release Ratio".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.5),
                    default_text: None,
                },
                ParamDef {
                    id: "sustain_level".into(),
                    name: "Sustain Level".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.5),
                    default_text: None,
                },
                ParamDef {
                    id: "attack_curve".into(),
                    name: "Attack Curve".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "decay_curve".into(),
                    name: "Decay Curve".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
                ParamDef {
                    id: "amplitude".into(),
                    name: "Amplitude".into(),
                    param_type: ParamType::Number,
                    default_number: Some(1.0),
                    default_text: None,
                },
                ParamDef {
                    id: "length_beats".into(),
                    name: "Length (beats)".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.5),
                    default_text: None,
                },
                ParamDef {
                    id: "fit_to_gap".into(),
                    name: "Fit To Gap (0/1)".into(),
                    param_type: ParamType::Number,
                    default_number: Some(0.0),
                    default_text: None,
                },
            ],
        },
    ]
}
